### ISSUE TITLE
apply the changes of lbm-sdk v0.47.0-alpha1

### ISSUE THREAD

**Issue by zemyblue** [Finschia/finschia-js#67]
### The changes of lbm-sdk v0.47.0-alpha1

- [x] refactor: remove legacy REST APIs - [lbm-sdk#807](https://github.com/line/lbm-sdk/pull/807) 
  - nothing to respond to.
- [x] feat(x/foundation): remove unnecessary gov-mint feature - [lbm-sdk#848](https://github.com/line/lbm-sdk/pull/848)
- [x] fix!: introduce codespace into x/collection,token - [lbm-sdk#849](https://github.com/line/lbm-sdk/pull/849)
  - nothing to response to.
- [x] fix!: update x/collection,token proto - [lbm-sdk#863](https://github.com/line/lbm-sdk/pull/863)
- [x] feat!: add MultiSend deactivation - [lbm-sdk#876](https://github.com/line/lbm-sdk/pull/876)
- [x] fix: remove some x/token,collection queries on listable collections - [lbm-sdk#881](https://github.com/line/lbm-sdk/pull/881)
- [x] feat!: add custom GetBlockWithTxs for lbm - [lbm-sdk#891](https://github.com/line/lbm-sdk/pull/891)
- [x] feat!: remove the incompatible field index=14 in TxResponse - [lbm-sdk#892](https://github.com/line/lbm-sdk/pull/892)
